import 'package:get/get.dart';
import 'base_admin_controller.dart';
import '../models/school_admin_models.dart';

class AdminFeeController extends GetxController {
  final BaseAdminController base = Get.find<BaseAdminController>();

  Map<String, List<MonthlyFeeRecordModel>> get feeRecordsByStudent {
    final allRecords = base.schoolDataService.getFeeRecords(
      base.currentSchoolId,
    );
    final Map<String, List<MonthlyFeeRecordModel>> map = {};
    for (var r in allRecords) {
      map.putIfAbsent(r.studentId, () => []).add(r);
    }
    return map;
  }

  final selectedStudentId = ''.obs;

  void openStudentFeeDetails(String studentId) {
    selectedStudentId.value = studentId;
    Get.toNamed('/admin-student-fee-details');
  }

  double computeTotalDues(String studentId) {
    final records = feeRecordsByStudent[studentId];
    if (records == null) return 0.0;
    return records.fold(0.0, (sum, r) => sum + (r.remainingAmount));
  }

  void submitFeePayment(
    String studentId,
    double amount,
    String monthStr,
  ) async {
    if (base.isOffline.value) {
      Get.snackbar('Offline', 'Cannot accept payments offline');
      return;
    }

    final records = feeRecordsByStudent[studentId];
    if (records == null) return;

    final record = records.firstWhereOrNull(
      (r) => r.status == FeeStatus.pending,
    );

    if (record == null) {
      Get.snackbar('Error', 'No pending fee record found for this student');
      return;
    }

    final newPaid = record.paidAmount + amount;
    final newStatus = (record.totalAmount - newPaid) <= 0
        ? FeeStatus.paid
        : FeeStatus.pending;

    final transaction = FeeTransactionModel(
      id: DateTime.now().millisecondsSinceEpoch.toString(),
      amount: amount,
      date: DateTime.now(),
      remarks: 'Payment of $amount for $monthStr',
      status: TransactionStatus.successful,
    );

    final updatedRecord = record.copyWith(
      paidAmount: newPaid,
      status: newStatus,
      updatedAt: DateTime.now(),
      transactions: [...record.transactions, transaction],
    );

    await base.schoolDataService.updateFeeRecord(
      base.currentSchoolId,
      updatedRecord,
    );
    Get.snackbar('Success', 'Payment of $amount processed');
  }

  void generateBulkFees(int month, int year, double amount) async {
    final students = base.schoolDataService.getStudents(base.currentSchoolId);
    final List<MonthlyFeeRecordModel> newRecords = [];

    for (var student in students) {
      newRecords.add(
        FeeRecordModel(
          id: '', // Firestore will generate
          schoolId: base.currentSchoolId,
          studentId: student.id,
          month: month,
          year: year,
          status: FeeStatus.pending,
          totalAmount: amount,
          paidAmount: 0.0,
          updatedAt: DateTime.now(),
        ),
      );
    }

    await base.schoolDataService.addFeeRecordsBatch(
      base.currentSchoolId,
      newRecords,
    );
    Get.snackbar(
      'Success',
      'Bulk fees generated for ${students.length} students',
    );
  }

  void assignIndividualFee({
    required String studentId,
    required int month,
    required int year,
    required double amount,
    String? remarks,
  }) async {
    final record = FeeRecordModel(
      id: '', // Generated by Firestore
      schoolId: base.currentSchoolId,
      studentId: studentId,
      month: month,
      year: year,
      status: FeeStatus.pending,
      totalAmount: amount,
      paidAmount: 0.0,
      remarks: remarks,
      updatedAt: DateTime.now(),
    );

    await base.schoolDataService.addFeeRecord(base.currentSchoolId, record);
    Get.snackbar('Success', 'Fee assigned to student');
  }

  void approvePayment(FeeRecordModel record) async {
    final transactions = List<FeeTransactionModel>.from(record.transactions);
    final index = transactions.indexWhere(
      (t) => t.status == TransactionStatus.processing,
    );

    if (index == -1) {
      Get.snackbar('Error', 'No pending payment found to approve');
      return;
    }

    final tx = transactions[index];
    final updatedTx = tx.copyWith(status: TransactionStatus.successful);
    transactions[index] = updatedTx;

    final newPaid = record.paidAmount + tx.amount;
    final newStatus = (record.totalAmount - newPaid) <= 0
        ? FeeStatus.paid
        : FeeStatus.pending;

    final updatedRecord = record.copyWith(
      paidAmount: newPaid,
      status: newStatus,
      transactions: transactions,
      updatedAt: DateTime.now(),
    );

    await base.schoolDataService.updateFeeRecord(
      base.currentSchoolId,
      updatedRecord,
    );
    Get.snackbar('Success', 'Payment of ${tx.amount} approved');
  }

  void rejectPayment(FeeRecordModel record, String reason) async {
    // Revert to pending, maybe add a remark
    final updatedRecord = record.copyWith(
      status: FeeStatus.pending,
      remarks: 'Payment rejected: $reason',
      updatedAt: DateTime.now(),
    );

    await base.schoolDataService.updateFeeRecord(
      base.currentSchoolId,
      updatedRecord,
    );
    Get.snackbar('Alert', 'Payment rejected');
  }
}
