import 'package:flutter/material.dart';
import 'package:get/get.dart';
import '../controllers/school_admin_controller.dart';
import '../models/school_admin_models.dart';

class ArchiveReportDetailView extends GetView<SchoolAdminController> {
  const ArchiveReportDetailView({super.key});

  @override
  Widget build(BuildContext context) {
    final args = Get.arguments ?? {};
    final isStudent = args['isStudent'] == true;

    // Check for new StudentSummaryReportModel
    if (args['report'] != null) {
      final report = args['report'];
      return Scaffold(
        appBar: AppBar(title: const Text('Student Summary Report')),
        body: _buildStudentSummaryReport(report),
        floatingActionButton: Obx(
          () => FloatingActionButton(
            onPressed: controller.isOffline.value
                ? null
                : () => Get.snackbar('Download', 'Mock PDF downloaded'),
            backgroundColor: controller.isOffline.value
                ? Colors.grey
                : Colors.blue,
            child: const Icon(Icons.download),
          ),
        ),
      );
    }

    // Fall back to old model lookup by ID
    final id = args['id'] as String?;
    if (id == null) {
      return Scaffold(
        appBar: AppBar(title: const Text('Error')),
        body: const Center(child: Text('No report data provided')),
      );
    }

    return Scaffold(
      appBar: AppBar(
        title: Text('${isStudent ? 'Student' : 'Teacher'} Archive Report'),
      ),
      body: Obx(() {
        if (isStudent) {
          final report = controller.studentArchiveReportsByStudentId[id];
          if (report == null) {
            return const Center(child: CircularProgressIndicator());
          }
          return _buildStudentReport(report);
        } else {
          final report = controller.teacherArchiveReportsByTeacherId[id];
          if (report == null) {
            return const Center(child: CircularProgressIndicator());
          }
          return _buildTeacherReport(report);
        }
      }),
      floatingActionButton: Obx(
        () => FloatingActionButton(
          onPressed: controller.isOffline.value
              ? null
              : () => Get.snackbar('Download', 'Mock PDF downloaded'),
          backgroundColor: controller.isOffline.value
              ? Colors.grey
              : Colors.blue,
          child: const Icon(Icons.download),
        ),
      ),
    );
  }

  Widget _buildStudentSummaryReport(dynamic report) {
    return SingleChildScrollView(
      padding: const EdgeInsets.all(16),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          _row('Report Generated', report.generatedAt.toString()),
          _row('Generated By', report.generatedByRole),
          const Divider(),
          _section('Personal Info'),
          _row('Name', report.name),
          _row('Roll No', report.rollNo),
          _row('Class', report.classNumber),
          const Divider(),
          _section('Parent/Guardian Info'),
          _row('Email', report.parentEmail),
          _row('CNIC', report.parentCnic),
          _row('Contact', report.contactNumber),
          _row('Address', report.address),
          const Divider(),
          _section('Academic History'),
          _row('Joined', report.joiningDate.toString().split(' ')[0]),
          if (report.inactiveAt != null)
            _row('Became Inactive', report.inactiveAt.toString().split(' ')[0]),
          if (report.archivedAt != null)
            _row('Archived', report.archivedAt.toString().split(' ')[0]),
          const Divider(),
          _section('Fee Summary'),
          _row('', report.feeSummaryText),
          const Divider(),
          _section('Attendance Summary'),
          _row('', report.attendanceSummaryText),
          const SizedBox(height: 20),
          const Center(
            child: Text(
              '--- END OF ARCHIVE REPORT ---',
              style: TextStyle(color: Colors.grey),
            ),
          ),
        ],
      ),
    );
  }

  Widget _buildStudentReport(StudentArchiveReportModel s) {
    return SingleChildScrollView(
      padding: const EdgeInsets.all(16),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          _row('Report Generated', s.generatedAt.toString()),
          const Divider(),
          _section('Personal Info'),
          _row('Name', s.name),
          _row('Roll No', s.rollNo),
          _row('Class', s.classNumber),
          _row('Parent Email', s.parentEmail),
          _row('Parent CNIC', s.parentCnic),
          const Divider(),
          _section('Academic History'),
          _row('Joined', s.joiningDate.toString().split(' ')[0]),
          if (s.struckOffDate != null)
            _row('Struck Off', s.struckOffDate.toString().split(' ')[0]),
          _row('Attendance', s.attendanceSummary),
          _row('Last Paid Dues', s.lastFeeSummary.toString()),
          const SizedBox(height: 20),
          const Center(
            child: Text(
              '--- END OF ARCHIVE REPORT ---',
              style: TextStyle(color: Colors.grey),
            ),
          ),
        ],
      ),
    );
  }

  Widget _buildTeacherReport(TeacherArchiveReportModel t) {
    return SingleChildScrollView(
      padding: const EdgeInsets.all(16),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          _row('Report Generated', t.generatedAt.toString()),
          const Divider(),
          _section('Teacher Info'),
          _row('Name', t.name),
          _row('Subject', t.subject),
          _row('Qualification', t.qualification),
          _row('Experience', '${t.experienceYears} Years'),
          const Divider(),
          _section('Tenure'),
          _row('Joined', t.joiningDate.toString().split(' ')[0]),
          if (t.removedDate != null)
            _row('Removed', t.removedDate.toString().split(' ')[0]),
          _row('Classes Taught', t.classesTaught.join(', ')),
        ],
      ),
    );
  }

  Widget _section(String title) {
    return Padding(
      padding: const EdgeInsets.symmetric(vertical: 8),
      child: Text(
        title,
        style: const TextStyle(
          fontSize: 18,
          fontWeight: FontWeight.bold,
          color: Colors.blueGrey,
        ),
      ),
    );
  }

  Widget _row(String label, String value) {
    return Padding(
      padding: const EdgeInsets.symmetric(vertical: 4),
      child: Row(
        children: [
          SizedBox(
            width: 120,
            child: Text(
              label,
              style: const TextStyle(fontWeight: FontWeight.bold),
            ),
          ),
          Expanded(child: Text(value)),
        ],
      ),
    );
  }
}

