import 'package:get/get.dart';
import '../models/teacher_models.dart';
import '../services/teacher_dashboard_service.dart';
import '../controllers/teacher_controller.dart';
import '../../../services/school_data_service.dart';
import '../../../services/auth_service.dart';
import '../../../data/models/academic_attendance_model.dart' as academic;

class TeacherAttendanceController extends GetxController {
  final _dashboardService = Get.find<TeacherDashboardService>();
  // Still need TeacherController for offline status until we refactor that
  final _teacherController = Get.find<TeacherController>();

  // --- State ---
  List<ClassTimetableSlotModel> get assignedClasses {
    final timetable = _dashboardService.teacherTimetable;
    final assigned = _dashboardService.getAssignedClasses();

    final Map<String, ClassTimetableSlotModel> uniqueMap = {};

    for (var slot in timetable) {
      final key = '${slot.classNumber}_${slot.subjectName}';
      if (!uniqueMap.containsKey(key)) {
        uniqueMap[key] = slot;
      }
    }

    for (var assignment in assigned) {
      final key = '${assignment.classNumber}_${assignment.subjectName}';
      if (!uniqueMap.containsKey(key)) {
        uniqueMap[key] = ClassTimetableSlotModel(
          id: assignment.id,
          classId: assignment.classNumber,
          classNumber: assignment.classNumber,
          day: '',
          subjectId: assignment.subjectName,
          subjectName: assignment.subjectName,
          teacherId: assignment.teacherId,
          teacherName: '',
          startTime: '',
          endTime: '',
          roomNumber: '',
        );
      }
    }

    final list = uniqueMap.values.toList();
    list.sort((a, b) => a.classNumber.compareTo(b.classNumber));
    return list;
  }

  RxBool get isOffline => _teacherController.isOffline;

  final selectedClassId = ''.obs;
  ClassTimetableSlotModel? selectedSlot;
  final studentsAttendance = <StudentAttendanceModel>[].obs;
  final alreadySubmittedToday = false.obs;
  final isLoading = false.obs;

  void selectClass(String slotId) {
    selectedClassId.value = slotId;
    selectedSlot = assignedClasses.firstWhereOrNull((s) => s.id == slotId);
    alreadySubmittedToday.value = false;
    if (selectedSlot != null) {
      fetchStudents(selectedSlot!.classNumber);
    }
  }

  Future<void> fetchStudents(String classNumber) async {
    isLoading.value = true;
    try {
      final students = await _dashboardService.getStudentsForClass(classNumber);
      final attendanceList = students
          .map(
            (s) => StudentAttendanceModel(
              id: s.id, // Use student id
              name: s.name,
              rollNo: s.rollNo,
              status: AttendanceStatus.present, // Default
            ),
          )
          .toList();

      studentsAttendance.assignAll(attendanceList);
    } catch (e) {
      Get.snackbar('Error', 'Failed to load students: $e');
    } finally {
      isLoading.value = false;
    }
  }

  Future<void> submitAttendance() async {
    if (isOffline.value) {
      Get.snackbar('Error', 'Cannot submit attendance while offline');
      return;
    }
    if (alreadySubmittedToday.value) {
      Get.snackbar('Error', 'Attendance already submitted for today');
      return;
    }
    if (selectedSlot == null) {
      Get.snackbar('Error', 'No class slot selected');
      return;
    }

    isLoading.value = true;
    try {
      final schoolDataService = Get.find<SchoolDataService>();
      final session = _dashboardService.userId;
      final schoolId = Get.find<AuthService>().session.value?.schoolId;

      if (schoolId == null) throw 'No school ID found';

      for (var student in studentsAttendance) {
        final record = academic.SubjectAttendanceRecord(
          id: '', // Generated by firestore helper
          studentId: student.id,
          studentName: student.name,
          classId: selectedSlot!.classNumber, // Usually classId or classNumber
          subjectId: selectedSlot!.subjectName, // Use subject name or ID
          teacherId: session,
          date: DateTime.now(),
          status: student.status == AttendanceStatus.present
              ? academic.SubjectAttendanceStatus.present
              : (student.status == AttendanceStatus.absent
                    ? academic.SubjectAttendanceStatus.absent
                    : academic.SubjectAttendanceStatus.leave),
          updatedAt: DateTime.now(),
        );

        await schoolDataService.saveSubjectAttendance(schoolId, record);
      }

      alreadySubmittedToday.value = true;
      Get.snackbar('Success', 'Attendance submitted successfully');
      Get.back(); // Go back to classes list
    } catch (e) {
      Get.snackbar('Error', e.toString());
    } finally {
      isLoading.value = false;
    }
  }
}
